---
title: Pushkarev blog
timezone: Asia/Krasnoyarsk
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: gfmac.58@gmail.com
description: Написать удивительное описание для вашего нового сайта здесь. Вы можете
  отредактировать эту строку в _config.yml. Он появится в вашем документе мета голове
  (для результатов поиска Google) и в описании feed.xml сайта.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
